import faker from 'faker';
import config from './config';

export default {
  'User signin and create document': browser =>
    browser
      .maximizeWindow()
      .url(config.url)
      .waitForElementVisible('body')
      .click('#signin')
      .setValue('Input[name=email]', 'love@handle.com')
      .setValue('Input[name=password]', 'love')
      .click('button')
      .pause(1000)
      .assert.containsText('h3#fiddle-text',
      'Welcome to Meek - Document Management System')
      .waitForElementVisible('#menuBar')
      .click('#menuBar')
      .click('a[href="/create-document"')
      .waitForElementVisible('a[href="/create-document"')
      .assert.urlContains('create-document')
      .click('body')
      .waitForElementVisible('Input[name=title]')
      .setValue('Input[name=title]', faker.lorem.word())
      .click('button.mce-close')
      .click('.mce-i-code')
      .setValue('.mce-textbox', faker.lorem.paragraphs())
      .click('.mce-floatpanel .mce-container-body button')
      .waitForElementVisible('button.submitBtn')
      .setValue('Input[name=type]', faker.lorem.word())
      .click('button.submitBtn')
      .pause(2000)
      .assert.urlContains('my-documents')
      .end(),

  'User edit document': browser =>
    browser
      .maximizeWindow()
      .url(config.url)
      .waitForElementVisible('body')
      .click('#signin')
      .setValue('Input[name=email]', 'love@handle.com')
      .setValue('Input[name=password]', 'love')
      .click('button')
      .waitForElementVisible('#menuBar')
      .click('#menuBar')
      .click('a[href="/my-documents"')
      .waitForElementVisible('a[href="/my-documents"')
      .assert.urlContains('my-documents')
      .click('body')
      .waitForElementVisible('tr:last-child td:nth-child(2)')
      .click('tr:last-child td:nth-child(2)  a')
      .assert.urlContains('view')
      .waitForElementVisible('button.btn-floating')
      .click('button.btn-floating')
      .assert.urlContains('documents')
      .setValue('Input[name=title]', faker.lorem.word())
      .click('button.mce-close')
      .click('.mce-i-code')
      .setValue('.mce-textbox', faker.lorem.word(2))
      .click('.mce-floatpanel .mce-container-body button')
      .waitForElementVisible('button.submitBtn')
      .setValue('Input[name=type]', faker.lorem.word(1))
      .click('button.submitBtn')
      .pause(2000)
      .assert.urlContains('my-documents')
      .end(),

  'User delete document': browser =>
    browser
      .maximizeWindow()
      .url(config.url)
      .waitForElementVisible('body')
      .click('#signin')
      .setValue('Input[name=email]', 'love@handle.com')
      .setValue('Input[name=password]', 'love')
      .click('button')
      .waitForElementVisible('#menuBar')
      .click('#menuBar')
      .click('a[href="/my-documents"]')
      .assert.urlContains('my-documents')
      .click('body')
      .waitForElementVisible('tr:last-child td:nth-child(2)')
      .click('tr:last-child td:nth-child(2)  a')
      .pause(2000)
      .assert.urlContains('view')
      .click('button.btn-floating.cyan')
      .pause(2000)
      .click('button.btn.white-text')
      .pause(2000)
      .assert.urlContains('my-documents')
      .end()
};
