export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const DISPLAY_ALL_DOCUMENTS = 'DISPLAY_ALL_DOCUMENTS';
export const DISPLAY_MY_DOCUMENTS = 'DISPLAY_MY_DOCUMENTS';
// export const DISPLAY_UPDATED_DOCUMENT = 'DISPLAY_UPDATED_DOCUMENT';
// export const DELETE_USER_DOCUMENT_SUCCESS = 'DELETE_USER_DOCUMENT_SUCCESS';
export const UPDATE_DOCUMENT_SUCCESS = 'UPDATE_DOCUMENT_SUCCESS';
export const DELETE_DOCUMENT = 'DELETE_DOCUMENT';
export const DOC_FETCHED = 'DOC_FETCHED';
